### PR TITLE
Fix verb methods context handling

### PR DESCRIPTION
**Pull request by nunofgs**
Verb methods would hang indefinitely with the new request [2.54.1](https://github.com/request/request/releases/tag/v2.54.1) version.

### CODE REVIEW

**Comment by kikoanis** [comment]
+1 for this PR

This solves the hanging issue on some requests. Either this or just you have to be specific about the Request library version.

**Comment by fixe** [comment]
ping @leukhin

**Comment by leukhin** [comment]
Merged. Thanks!

**Comment by fixe** [comment]
@leukhin can you release a new version to npm please? Thanks.

**Comment by leukhin** [comment]
@fixe Done!

**Pull request merged**
